spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kinder?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: db/changelog-master.xml

school:
  startFreeHours: 7
  endFreeHours: 12
